apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
  namespace: {{ .Values.namespace.name }}
data:
  DB_USERNAME: {{ .Values.database.config.username | quote }}
  DB_NAME: {{ .Values.database.config.name | quote }}
  DB_HOST: {{ .Values.database.config.host | quote }}
  DB_PORT: {{ .Values.database.config.port | quote }} 
