apiVersion: v1
kind: Service
metadata:
  name: app-server
  namespace: dev
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
  - name: "3112"
    protocol: TCP
    port: 3112
    targetPort: 3112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  labels:
    name: app-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: app-server
        image: tomiwasalau01/tommyjumper:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3112
          initialDelaySeconds: 5
          timeoutSeconds: 2
        # readinessProbe:
        #   httpGet:
        #     path: "/readiness_check"
        #     port: 5151
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          value: app-db
      restartPolicy: Always
