kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
  labels:
    type: local
    app: app-db
  namespace: dev
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: app-db
  namespace: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-db
  labels:
    app: app-db
  namespace: dev
spec:
  type: NodePort
  selector:
    app: app-db
  ports:
   - port: 5432
     targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: app-db-headless
  labels:
    app: app-db
  namespace: dev
spec:
  clusterIP: None
  selector:
    app: app-db
  ports:
   - port: 5432
     targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-db
  namespace: dev
spec:
  serviceName: app-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: app-db
          image: tomiwasalau01/app-db:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim