mode: "deployment"
config:
  exporters:
    jaeger:
      endpoint: "jaeger-collector.observability.svc.cluster.local:14250"
      tls:
        insecure: true

  # extensions:
  #   health_check:
  #     endpoint: "0.0.0.0:13133"

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024

  receivers:
    # jaeger:
    #   protocols:
    #     grpc:
    #       endpoint: "0.0.0.0:14250"
    #     thrift_http:
    #       endpoint: "0.0.0.0:14268"
    #     thrift_compact:
    #       endpoint: "0.0.0.0:6831"
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  service:
    # extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [jaeger]
