mode: "deployment"
config:
  exporters:
    # Export traces to Jaeger using OTLP exporter
    otlp:
      endpoint: jaeger-collector.observability.svc.cluster.local:4317
      tls:
        insecure: true
    # Debug exporter for troubleshooting
    debug:
      verbosity: detailed

  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"

  processors:
    batch:
      timeout: 5s
      send_batch_size: 512
      send_batch_max_size: 1024

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp, debug]
