{
 "title": "TM-dashboard",
 "tags": [ "monitoring" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "host", "label": "host", "query": { "query": "label_values()" } },
   {
    "name": "step",
    "label": "step",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": {
     "query": "label_values(node_cpu_seconds_total,cpu)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(node_boot_time_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "number of nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(count by (cpu)(node_cpu_seconds_total{host='$host'})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    { "expr": "avg_over_time(up[1h]) * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backend Response duration",
   "type": "timeseries",
   "description": "This panel displays information about all the traces generated by Jaeger.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "query": "c2053b9", "service": "backend" }
   ]
  },
  {
   "title": "Frontend Response Duration",
   "type": "timeseries",
   "description": "This panel displays information about all the traces generated by Jaeger.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "query": "c2053b9", "service": "frontend" }
   ]
  },
  {
   "title": "% Error requests per day",
   "type": "timeseries",
   "description": "This panel shows the total percent of 40x and 50x error requests per service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count (rate(flask_http_request_duration_seconds_count{container=~\"backend\",status=~\"(^50\\\\d|^40\\\\d)\"}[$interval]))) / (count (rate(flask_http_request_duration_seconds_count{container=~\"backend\"}[$interval])))",
     "legendFormat": "backend (50x & 40x)"
    }
   ]
  },
  {
   "title": "% Successful requests per day",
   "type": "timeseries",
   "description": "This panel shows the total percentage of successful requests per service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(count (rate(flask_http_request_duration_seconds_count{container=~\"backend\",status=~\"^200\"}[$interval]))) * 100/ (count (rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\"}[$interval])))",
     "legendFormat": "backend"
    },
    {
     "expr": "(count (rate(flask_http_request_duration_seconds_count{container=~\"frontend\",status=~\"^200\"}[$interval]))) * 100/ (count (rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\"}[$interval])))",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$server\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",instance=\"$server\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_nfsd_disk_bytes_read_total{instance=\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_nfsd_disk_bytes_written_total{instance=\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_seconds_total{instance=\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$server\"} - node_memory_MemFree_bytes{instance=\"$server\"}  - node_memory_Buffers_bytes{instance=\"$server\"} - node_memory_Cached_bytes{instance=\"$server\"}) / node_memory_MemTotal_bytes{instance=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server\"} - node_memory_MemFree_bytes{instance=\"$server\"} - node_memory_Buffers_bytes{instance=\"$server\"} - node_memory_Cached_bytes{instance=\"$server\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$server\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$server\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$server\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Average cpu %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{host=\"$host\", mode='idle'}[$interval])))*100"
    }
   ]
  },
  {
   "title": "cpu usage (node)",
   "type": "timeseries",
   "description": "Average CPU usage percentage across all CPU cores on a node over the last 5 minutes. The result will be a value between 0% and 100%, where 0% indicates that all CPU cores were fully utilized, and 100% indicates that all CPU cores were idle",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='user', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='system', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='idle', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Response time per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{container=~\"backend\",status=\"200\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count{container=~\"backend\",status=\"200\"}[1m]))) * 1000\n\n",
     "legendFormat": "backend"
    },
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{container=~\"frontend\",status=\"200\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count{container=~\"frontend\",status=\"200\"}[1m]))) * 1000",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(prometheus_http_requests_total{code=~\"2.*\"})* 100/sum(prometheus_http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}