namespace:
  name: staging 

service:
  port: 5111
  type: ClusterIP

image:
  repository: tomiwasalau01/techtrends 
  tag: v2.0.0
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    memory: "128Mi"
    cpu: "500m"

ports:
  containerPort: 3111
  protocol: TCP

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111

readinessProbe:
  httpGet:
    path: /healthz
    port: 3111