namespace:
  name: prod 

service:
  port: 7111
  type: ClusterIP

replicaCount: 5

image:
  repository: tomiwasalau01/techtrends 
  tag: v2.0.0
  pullPolicy: Always

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    memory: 256Mi
    cpu: 500m

ports:
  containerPort: 3111
  protocol: TCP

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111

readinessProbe:
  httpGet:
    path: /healthz
    port: 3111
