apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends-app
    tag: techtrends-tag
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends-app
      tag: techtrends-tag
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends-app
        tag: techtrends-tag
    spec:
      containers:
      - image: tomiwasalau01/techtrends:v2.0.0
        name: techtrends
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3111
          protocol: TCP

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"    