apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends-app
    tag: techtrends-tag
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends-app
    tag: techtrends-tag
  type: ClusterIP
status:
  loadBalancer: {}