namespace:
  name: dev

database:
  enabled: true
  replicaCount: 1
  port: 5432
  image:
    repository: tomiwasalau01/app-db
    tag: latest
    pullPolicy: IfNotPresent
  storage:
    capacity: 256Mi
    hostPath: "/mnt/data"
  config:
    username: "postgres"
    name: "postgres"
    host: "app-db"
    port: "5432"


