DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(256) NOT NULL,
    content VARCHAR(2046) NOT NULL,
    name VARCHAR(100)
);
